# Constants to initiate Company
NUMBER_OF_CLIENTS = 0
SELLING_PRICE = 1
MARKETING = 0
EFFICIENCY = 0
INNOVATION = 0
REVENUE = 0
COSTS = 0
PROFIT = 0

# Constants to initiate GameBox
TURN = 0
TOTAL_CLIENTS = 100
TOTAL_RESOURCES = 10
NUMBER_OF_PLAYERS = 2
NUMBER_OF_SQUARES = 39